version: '3.9'

services:
  map:
    image: 3liz/qgis-map-server:3.16
    environment:
      - QGSRV_SERVER_WORKERS=6
      - QGSRV_LOGGING_LEVEL=DEBUG
      - QGSRV_CACHE_ROOTDIR=/web
      - QGSRV_CACHE_SIZE=100
      - QGSRV_SERVER_TIMEOUT=300
    volumes:
      - ./qgis_projects:/web

  mapproxy:
    image: kartoza/mapproxy
    environment:
      - PRODUCTION=true
      - PROCESSES=4
      - CHEAPER=2
      - THREADS=10
      - MAPPROXY_USER_ID=1000
      - MAPPROXY_GROUP_ID=1000
      - ALLOW_LISTING=True
      - LOGGING=true
    volumes:
      - ./mapproxy_configuration:/mapproxy
    depends_on:
      - map

  nginx:
    image: nginx
    environment:
      - NGINX_HOST=mapproxy
    volumes:
      - ./web:/web
      - ./sites-enabled:/etc/nginx/conf.d:ro
      - ./web/nginx_conf.sh:/docker-entrypoint.d/nginx_conf.sh
    logging:
      driver: json-file
      options:
        max-size: 200m
        max-file: '10'
    depends_on:
      - mapproxy
      - map
    ports:
    - "80:80"

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gistda.or.th
      PGADMIN_DEFAULT_PASSWORD: 123456
      MAX_LOGIN_ATTEMPTS: 1000
    ports:
      - "5050:80"
    volumes:
       - pgadmin:/var/lib/pgadmin

volumes:
    pgadmin:
    db:

