# #####################################################################
#                 MapProxy example configuration
# #####################################################################
#
# This is _not_ a runnable configuration, but it contains most
# available options in meaningful combinations.
#
# Use this file in addition to the documentation to see where and how
# things can be configured.


services:
  demo:
  wms:
    # only offer WMS 1.1.1
    versions: ['1.1.1', '1.3.0']
    # supported SRS for this WMS
    srs: ['EPSG:4326', 'EPSG:3857']
    # force the layer extents (BBOX) to be displayed in this SRS
    bbox_srs: ['EPSG:4326']
    # limit the supported image formats.
    image_formats: ['image/jpeg', 'image/png', 'image/gif', 'image/GeoTIFF', 'image/tiff']
    # return an OGC service exception when one or more sources return errors
    # or no response at all (e.g. timeout)
    on_source_errors: raise

    # some WMS clients do not send all required parameters in feature info
    # requests, MapProxy ignores these errors unless you set strict to true.
    strict: true

    # list of feature info types the server should offer
    featureinfo_types: ['text', 'html', 'xml']

    md:
      # metadata used in capabilities documents
      title: Mapproxy demo map
      abstract: The map showing how QGIS Server interacts with Mapproxy.
      online_resource: http://kartoza.com/
      contact:
        person: Kartoza
        position: GIS Manager
        organization:
        address:
        city:
        postcode:
        country: south Africa
        phone:
        email:
      access_constraints:
        Insert license and copyright information for this service.
      fees: 'None'
  tms:
    use_grid_names: true
  wmts:
    restful: true
    restful_template: '/{Layer}/{TileMatrixSet}/{TileMatrix}/{TileCol}/{TileRow}.{Format}'
    kvp: true
  kml:
    use_grid_names: true

layers:
  - name: Hillshade
    title: Hillshade
    sources: [hillshade_cache]

  - name: SRTM
    title: SRTM 30m
    sources: [srtm_cache]

  - name: airports
    title: Airports
    sources: [airports_cache]

  - name: sphere_streets
    title: GISTDA sphere Streets
    sources: [sphere_streets_cache]

  - name: sphere_images
    title: GISTDA sphere Images
    sources: [sphere_images_cache]

  - name: sphere_custom
    title: sphere custom layer
    sources: [sphere_custom_cache]

  - name: bluemarble
    title: Bluemarble
    sources: [bluemarble_cache]

  - name: bluemarble_no_source
    title: Bluemarble (No source)
    sources: [bluemarble_cache_no_source]

caches:
  
  airports_cache:
    sources: [airports_wms]
    grids: [osm_grid]
    meta_size: [5,5]
    meta_buffer: 20
    concurrent_tile_creators: 2
    cache:
      type: mbtiles
      filename: ./cache_data/airports.mbtiles

  srtm_cache:
    sources: [srtm_wms]
    grids: [osm_grid]
    meta_size: [5,5]
    meta_buffer: 20
    concurrent_tile_creators: 2
    cache:
      type: file
      directory: ./cache_data/srtm_cache
    format: custom_format

  hillshade_cache:
    sources: [hillshade_wms]
    grids: [osm_grid]
    meta_size: [5,5]
    meta_buffer: 20
    concurrent_tile_creators: 2
    cache:
      type: mbtiles
      filename: ./cache_data/hillshade.mbtiles

  sphere_streets_cache:
    sources: [sphere_streets_wms]
    grids: [osm_grid]
    meta_size: [5,5]
    meta_buffer: 20
    concurrent_tile_creators: 2

  sphere_images_cache:
    sources: [sphere_images_wms]
    grids: [osm_grid]
    meta_size: [5,5]
    meta_buffer: 20
    concurrent_tile_creators: 2

  sphere_custom_cache:
    sources: [sphere_custom_wms]
    grids: [osm_grid]
    meta_size: [5,5]
    meta_buffer: 20
    concurrent_tile_creators: 2

  bluemarble_cache:
    sources: [bluemarble_wms]
    grids: [osm_grid]
    meta_size: [5,5]
    meta_buffer: 20
    concurrent_tile_creators: 2

  bluemarble_cache_no_source:
    sources: []
    grids: [GLOBAL_MERCATOR]
    upscale_tiles: 7
    cache:
      type: file
      directory: /mapproxy/cache_data/bluemarble_cache_no_source
      directory_layout: tms
    format: custom_format

sources:
  hillshade_wms:
    coverage:
      bbox: [20, -9.99999999998001, 59.999999999984, 40]
      bbox_srs: EPSG:4326
    type: wms
    image:
      transparent_color: '#ffffff'
      transparent_color_tolerance: 20
    wms_opts:
      version: 1.3.0
      featureinfo: True
    req:
      url: http://map:8080/ows/?map=project.qgs
      layers: Hillshade
      transparent: true
    supported_formats: [png]
    supported_srs: ['EPSG:3857', 'CRS:84']

  srtm_wms:
    coverage:
      bbox: [20, -9.99999999998001, 59.999999999984, 40]
      bbox_srs: EPSG:4326
    type: wms
    image:
      transparent_color: '#ffffff'
      transparent_color_tolerance: 20
    wms_opts:
      version: 1.3.0
      featureinfo: True
    req:
      url: http://map:8080/ows/?map=project.qgs
      layers: SRTM
      transparent: true
    supported_formats: [png]
    supported_srs: ['EPSG:3857', 'CRS:84']

  airports_wms:
    coverage:
      bbox: [20, -9.99999999998001, 59.999999999984, 40]
      bbox_srs: EPSG:4326
    type: wms
    image:
      transparent_color: '#ffffff'
      transparent_color_tolerance: 20
    wms_opts:
      version: 1.3.0
      featureinfo: True
    req:
      url: http://map:8080/ows/?map=project.qgs
      layers: Airports
      transparent: true
    supported_formats: [png]
    supported_srs: ['EPSG:3857', 'CRS:84']

  sphere_streets_wms:
    type: wms
    image:
      transparent_color: '#ffffff'
      transparent_color_tolerance: 20
    wms_opts:
      version: 1.3.0
      featureinfo: True
    req:
      url: http://map:8080/ows/?map=project.qgs
      layers: sphere_streets
      transparent: true
    supported_formats: [png]
    supported_srs: ['EPSG:3857']

  sphere_images_wms:
    type: wms
    image:
      transparent_color: '#ffffff'
      transparent_color_tolerance: 20
    wms_opts:
      version: 1.3.0
      featureinfo: True
    req:
      url: http://map:8080/ows/?map=project.qgs
      layers: sphere_images
      transparent: true
    supported_formats: [jpeg]
    supported_srs: ['EPSG:3857']

  sphere_custom_wms:
    type: wms
    image:
      transparent_color: '#ffffff'
      transparent_color_tolerance: 20
    wms_opts:
      version: 1.3.0
      featureinfo: True
    req:
      url: http://map:8080/ows/?map=sphere_custom.qgs
      layers: sphere_custom
      transparent: true
    on_error:
       404:
          # response: '#ff0080'
          response: transparent
          cache: True
    supported_formats: [jpeg]
    supported_srs: ['EPSG:3857']

  bluemarble_wms:
    type: wms
    image:
      transparent_color: '#ffffff'
      transparent_color_tolerance: 20
    wms_opts:
      version: 1.3.0
      featureinfo: True
    req:
      url: http://map:8080/ows/?map=bluemarble.qgs
      layers: world.topo.bathy.200407.3_21600_108001
      transparent: true
    supported_formats: [jpeg]
    supported_srs: ['EPSG:3857']

grids:
  osm_grid:
    base: GLOBAL_MERCATOR
    srs: 'EPSG:3857'
    origin: nw 

globals:
  cache:
    meta_size: [6, 6]
    meta_buffer: 20
    lock_dir: './cache_data/locks'
    # where to store lockfiles for tile creation
    tile_lock_dir: './cache_data/tile_locks'
  http:
    ssl_no_cert_checks: true
